--[[-------------------------------------------------------------------]]--[[
							  
	Copyright wiltOS Technologies LLC, 2022
	
	Contact: www.wiltostech.com
		
----------------------------------------]]--


WOS_ALCS = WOS_ALCS or {}

WOS_ALCS.GRIP = WOS_ALCS.GRIP or {}
WOS_ALCS.GRIP.RIGHT = 0
WOS_ALCS.GRIP.LEFT = 1
WOS_ALCS.GRIP.BOTH = 2

WOS_ALCS.HUD = WOS_ALCS.HUD or {}
WOS_ALCS.HUD.NEWAGE = 1
WOS_ALCS.HUD.CLASSIC = 2
WOS_ALCS.HUD.FORCEMENU = 3
WOS_ALCS.HUD.HYBRID = 4

WOS_ALCS.SKILLMENU = WOS_ALCS.SKILLMENU or {}
WOS_ALCS.SKILLMENU.NEWAGE = 1
WOS_ALCS.SKILLMENU.CLASSIC = 2

WOS_ALCS.TRACE = WOS_ALCS.TRACE or {}
WOS_ALCS.TRACE.CLASSIC = 1
WOS_ALCS.TRACE.MINIMAL = 2
WOS_ALCS.TRACE.INTERP = 3
WOS_ALCS.TRACE.MINIMALINTERP = 4

WOS_ALCS.DUEL = WOS_ALCS.DUEL or {}
WOS_ALCS.DUEL.WON = 1
WOS_ALCS.DUEL.LOST = 2
WOS_ALCS.DUEL.DRAW = 3

WOS_ALCS.EXECUTE = WOS_ALCS.EXECUTE or {}
WOS_ALCS.EXECUTE.NO_TARGET = 0
WOS_ALCS.EXECUTE.ATTACKER = 1
WOS_ALCS.EXECUTE.VICTIM = 2

WOS_ALCS.DATADESC = WOS_ALCS.DATADESC or {}
WOS_ALCS.DATADESC.IS_TABLE = 1
WOS_ALCS.DATADESC.VARARG = 0
WOS_ALCS.DATADESC.BOOL = 2
WOS_ALCS.DATADESC.TBLBOOL = 3
WOS_ALCS.DATADESC.COLOR = 4
WOS_ALCS.DATADESC.TBLCOLOR = 5
WOS_ALCS.DATADESC.INT = 8
WOS_ALCS.DATADESC.TBLINT = 9
WOS_ALCS.DATADESC.STRING = 16
WOS_ALCS.DATADESC.TBLSTRING = 17
WOS_ALCS.DATADESC.VECTOR = 32
WOS_ALCS.DATADESC.TBLVECTOR = 33
WOS_ALCS.DATADESC.FLOAT = 64
WOS_ALCS.DATADESC.TBLFLOAT = 65
WOS_ALCS.DATADESC.ANGLE = 128
WOS_ALCS.DATADESC.TBLANGLE = 129
WOS_ALCS.DATADESC.UINT = 256
WOS_ALCS.DATADESC.TBLUINT = 257